// ESTE ARCHIVO AHORA SOLO EXPORTA LOS MODELOS DINÁMICOS.
// LAS LISTAS HARDCODED HAN SIDO ELIMINADAS PARA FORZAR EL USO DINÁMICO.
// SI EL CÓDIGO FALLA AQUÍ, ES PORQUE SE DEBE ACTUALIZAR EL CONSUMER.

export '../../core/models/catalog.dart';
