// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3tGiKFZpyCnP-0Njf7d9E_-zzLBVVqCM',
    appId: '1:1060028047975:web:433c518b19b0a65f6aeac2',
    messagingSenderId: '1060028047975',
    projectId: 'pasteleria180-2025',
    authDomain: 'pasteleria180-2025.firebaseapp.com',
    storageBucket: 'pasteleria180-2025.firebasestorage.app',
    measurementId: 'G-D9ZF2BNQVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_X0ziKaVTFfcrx2MsNRMZfP04eMWi3js',
    appId: '1:1060028047975:android:30b282c9f39facb46aeac2',
    messagingSenderId: '1060028047975',
    projectId: 'pasteleria180-2025',
    storageBucket: 'pasteleria180-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW7dtnxlU2Xi3jQesbcECkp_S_Gebn1ng',
    appId: '1:1060028047975:ios:b0d7409b058d42346aeac2',
    messagingSenderId: '1060028047975',
    projectId: 'pasteleria180-2025',
    storageBucket: 'pasteleria180-2025.firebasestorage.app',
    iosBundleId: 'com.one80.pasteleria.pasteleria180Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW7dtnxlU2Xi3jQesbcECkp_S_Gebn1ng',
    appId: '1:1060028047975:ios:b0d7409b058d42346aeac2',
    messagingSenderId: '1060028047975',
    projectId: 'pasteleria180-2025',
    storageBucket: 'pasteleria180-2025.firebasestorage.app',
    iosBundleId: 'com.one80.pasteleria.pasteleria180Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3tGiKFZpyCnP-0Njf7d9E_-zzLBVVqCM',
    appId: '1:1060028047975:web:59eb4976bd85ba0c6aeac2',
    messagingSenderId: '1060028047975',
    projectId: 'pasteleria180-2025',
    authDomain: 'pasteleria180-2025.firebaseapp.com',
    storageBucket: 'pasteleria180-2025.firebasestorage.app',
    measurementId: 'G-X35G11TZZ5',
  );
}
